import { GameObjects, Scene } from 'phaser';

import { heroAttackAtlasKey, heroIdleRunAtlasKey } from '../ui/heroArt';
import { ensureLuffyAnimations, LUFFY_ANIM_ATTACK, LUFFY_ANIM_IDLE, LUFFY_ANIM_RUN } from '../ui/heroAnimations';
import { applyDprZoom, DPR, LOGICAL_HEIGHT, LOGICAL_WIDTH } from '../systems/viewport';
import { Button, COLORS, FONT_FAMILY } from '../ui/kit';

const ATLAS_KEY = heroIdleRunAtlasKey('luffy');
const ATTACK_ATLAS_KEY = heroAttackAtlasKey('luffy');
const SCALE = 5;
const GROUND_Y = 420;
const SPEED_PRESETS = [0.1, 0.25, 0.5, 1, 2] as const;

/**
 * Standalone sprite-sheet-animation test (2026-08-31, per the repo owner) —
 * proving out frame-based character animation in this engine before any
 * real commission exists, using a placeholder sheet a friend drew (Luffy
 * idle/run, `public/test/luffy-sheet.png`). Deliberately isolated from the
 * real game: not on `MainMenuScene`, reachable only via `?spriteTest=1`
 * (`BootScene`'s existing debug-redirect convention) — kept alongside, not
 * replaced by, the real `UnitSprite` wiring added the same day (Luffy as an
 * animated hero in an actual battle, `heroArt.ts`'s `ANIMATED_HERO_NAMES`):
 * this scene is still the fast, isolated way to inspect raw frame timing
 * without a full battle running.
 *
 * The sheet's frames are hand-cut, not a fixed grid — width and height both
 * vary frame to frame (`public/test/luffy-atlas.json`, generated by
 * scanning for transparent-pixel gaps rather than hand-measured; see the
 * README changelog entry for the exact method). Phaser's grid-slicing
 * `load.spritesheet()` can't handle that; `load.atlas()` with per-frame
 * pixel rects is the actual fit. Each frame is trimmed *tight* to its own
 * ink (no padding), so `setOrigin(0.5, 1)` — Phaser's origin is a fraction
 * of *that* frame's own width/height, recomputed every frame — keeps the
 * character's feet anchored to the same point across every frame without
 * needing TexturePacker-style `sourceSize`/`spriteSourceSize` padding data.
 * The ground line is here specifically to make that verifiable at a
 * glance: if trimming ever stops being tight (a future sheet with baked-in
 * padding), the feet will visibly float off it frame to frame.
 *
 * `luffy-attack.png` is a second, separate sheet the repo owner added the
 * same way — a stretch-punch sequence long enough that it's laid out as two
 * rows rather than one very wide strip, which is why scanSpriteAtlas.ts grew
 * row-band detection (was single-row-only before). It also has a fist/
 * speed-line motion trail that fades to fully-transparent for a column
 * before resuming, which the tool's `--min-fragment-width` default now
 * folds back into its real neighbor instead of reading as its own tiny
 * frame — see that script's doc comment for how this was confirmed
 * (rendered the actual pixels, didn't guess). Deliberately *not* run
 * through `--stabilize`: a stretch punch has real, intentional horizontal
 * travel as the fist extends, which is exactly the motion that flag can't
 * tell apart from drift. A second Sprite isn't needed for either sheet —
 * Phaser's `sprite.play()` swaps texture to match whichever atlas an
 * animation's frames belong to, so one Sprite plays animations from either
 * atlas interchangeably.
 *
 * Animation definitions (per-frame timing, the attack's flurry-loop shape)
 * live in `src/ui/heroAnimations.ts`, shared with the real `UnitSprite`
 * wiring — see that file's doc comment for the anticipation/snap/hold/ease
 * read. This scene asks for `luffy-attack` on a continuous loop
 * (`repeat: -1` passed at play time) since it's meant for inspection; a
 * real combat hit plays it once (that animation's own default).
 */
export class SpriteTestScene extends Scene {
  private sprite!: GameObjects.Sprite;
  private currentAnim: 'idle' | 'run' | 'attack' = 'idle';
  private currentSpeed: number = 1;
  private frameLabel!: GameObjects.Text;
  private speedLabel!: GameObjects.Text;

  constructor() {
    super('SpriteTest');
  }

  preload(): void {
    this.load.atlas(ATLAS_KEY, 'test/luffy-sheet.png', 'test/luffy-atlas.json');
    this.load.atlas(ATTACK_ATLAS_KEY, 'test/luffy-attack.png', 'test/luffy-attack-atlas.json');
  }

  create(): void {
    this.cameras.main.setBackgroundColor('#1a1a2e');
    applyDprZoom(this);

    this.add
      .text(LOGICAL_WIDTH / 2, 40, 'SPRITE SHEET TEST', {
        fontFamily: FONT_FAMILY,
        fontSize: '15px',
        fontStyle: 'bold',
        color: COLORS.textAccent,
        resolution: DPR,
      })
      .setOrigin(0.5);
    this.add
      .text(LOGICAL_WIDTH / 2, 62, 'Placeholder art (not a commission) — proving the pipeline', {
        fontFamily: FONT_FAMILY,
        fontSize: '11px',
        color: COLORS.textDisabled,
        resolution: DPR,
      })
      .setOrigin(0.5);

    const ground = this.add.graphics();
    ground.lineStyle(1, 0x3a4258, 1);
    ground.lineBetween(LOGICAL_WIDTH / 2 - 100, GROUND_Y, LOGICAL_WIDTH / 2 + 100, GROUND_Y);

    ensureLuffyAnimations(this);

    this.sprite = this.add.sprite(LOGICAL_WIDTH / 2, GROUND_Y, ATLAS_KEY, 'idle-0').setOrigin(0.5, 1).setScale(SCALE);
    this.sprite.play(LUFFY_ANIM_IDLE);
    this.sprite.anims.timeScale = this.currentSpeed;
    this.sprite.on('animationupdate', () => {
      this.frameLabel.setText(`frame: ${this.sprite.frame.name}  (${this.sprite.frame.width}x${this.sprite.frame.height}px)`);
    });

    this.frameLabel = this.add
      .text(LOGICAL_WIDTH / 2, GROUND_Y + 40, '', { fontFamily: FONT_FAMILY, fontSize: '11px', color: COLORS.textDisabled, resolution: DPR })
      .setOrigin(0.5);

    const buttonY = LOGICAL_HEIGHT - 180;
    const idleButton = new Button(this, LOGICAL_WIDTH / 2 - 120, buttonY, 110, 42, 'Idle', null, '13px');
    const runButton = new Button(this, LOGICAL_WIDTH / 2, buttonY, 110, 42, 'Run', null, '13px');
    const attackButton = new Button(this, LOGICAL_WIDTH / 2 + 120, buttonY, 110, 42, 'Attack', null, '13px');
    const animButtons: Array<[Button, 'idle' | 'run' | 'attack']> = [
      [idleButton, 'idle'],
      [runButton, 'run'],
      [attackButton, 'attack'],
    ];
    animButtons.forEach(([button, anim]) => {
      button.setOnTap(() => {
        this.playAnim(anim);
        this.refreshButtonAccents(animButtons);
      });
    });
    this.refreshButtonAccents(animButtons);

    // Playback-speed selector (2026-08-31, per the repo owner) — added
    // specifically to help diagnose a "feet look like they're sliding"
    // report on the idle loop: at 1x it's hard to tell apart real per-frame
    // horizontal drift (the tight-crop atlas anchors each frame's bounding
    // box at its own center, not a fixed foot point — see scanSpriteAtlas.ts's
    // doc comment) from a simple frame-rate/eye artifact. 0.1x plays each
    // frame for ~1s at the idle rate, slow enough to step through by eye.
    const speedLabelY = buttonY + 46;
    this.speedLabel = this.add
      .text(LOGICAL_WIDTH / 2, speedLabelY, '', { fontFamily: FONT_FAMILY, fontSize: '11px', color: COLORS.textDisabled, resolution: DPR })
      .setOrigin(0.5);

    const speedButtonY = speedLabelY + 24;
    const speedButtonSpacing = 88;
    const speedButtons = SPEED_PRESETS.map((speed, i) => {
      const x = LOGICAL_WIDTH / 2 + (i - (SPEED_PRESETS.length - 1) / 2) * speedButtonSpacing;
      return new Button(this, x, speedButtonY, 80, 34, `${speed}x`, null, '12px');
    });
    speedButtons.forEach((button, i) => {
      button.setOnTap(() => {
        this.currentSpeed = SPEED_PRESETS[i];
        this.sprite.anims.timeScale = this.currentSpeed;
        this.refreshSpeedButtonAccents(speedButtons);
      });
    });
    this.refreshSpeedButtonAccents(speedButtons);

    const backButton = new Button(this, LOGICAL_WIDTH / 2, speedButtonY + 50, 130, 34, 'Back', () => this.scene.start('MainMenu'), '13px');
    backButton.setAccent(COLORS.cancelFill, COLORS.buttonStroke);
  }

  private playAnim(anim: 'idle' | 'run' | 'attack'): void {
    this.currentAnim = anim;
    if (anim === 'attack') {
      // Continuous loop for inspection purposes only — a real combat hit
      // uses luffy-attack's own default (repeat: 0, play once).
      this.sprite.play({ key: LUFFY_ANIM_ATTACK, repeat: -1 });
    } else {
      this.sprite.play(anim === 'idle' ? LUFFY_ANIM_IDLE : LUFFY_ANIM_RUN);
    }
    this.sprite.anims.timeScale = this.currentSpeed;
  }

  private refreshButtonAccents(animButtons: Array<[Button, 'idle' | 'run' | 'attack']>): void {
    animButtons.forEach(([button, anim]) => {
      const active = anim === this.currentAnim;
      button.setAccent(active ? COLORS.successFill : null, active ? COLORS.successStroke : null);
    });
  }

  private refreshSpeedButtonAccents(speedButtons: Button[]): void {
    speedButtons.forEach((button, i) => {
      const active = SPEED_PRESETS[i] === this.currentSpeed;
      button.setAccent(active ? COLORS.successFill : null, active ? COLORS.successStroke : null);
    });
    this.speedLabel.setText(`Speed: ${this.currentSpeed}x`);
  }
}
