import { GameObjects, Scene, Types } from 'phaser';

import { applyDprZoom, DPR, LOGICAL_HEIGHT, LOGICAL_WIDTH } from '../systems/viewport';
import { Button, COLORS, FONT_FAMILY } from '../ui/kit';

const ATLAS_KEY = 'luffy-test';
const ATTACK_ATLAS_KEY = 'luffy-attack-test';
const SCALE = 5;
const GROUND_Y = 420;
const SPEED_PRESETS = [0.1, 0.25, 0.5, 1, 2] as const;

/**
 * Per-frame durations (ms) for `luffy-attack`, replacing a flat frameRate —
 * see the doc comment above `buildAttackFrames()` for the read behind these
 * numbers and why frames 11-17 repeat instead of playing once.
 */
const ATTACK_WINDUP_DURATIONS = [90, 70, 60, 90, 50, 40, 35, 30]; // 0-7: anticipation, held longest at the cocked-back peak (index 3), snapping into the thrust
const ATTACK_IMPACT_DURATIONS = [120, 40, 35]; // 8-10: first punch lands at max extension (held), then a brief recovery
const ATTACK_PUNCH_CYCLE_DURATIONS = [35, 30, 30, 35, 50, 30, 30]; // 11-17: one punch (coiled -> extend -> begin retract), repeated for the flurry
const ATTACK_EASE_DURATIONS = [60, 90, 120, 160]; // 18-21: settling back to guard, progressively slower
const ATTACK_FLURRY_REPEATS = 3;

/**
 * Standalone sprite-sheet-animation test (2026-08-31, per the repo owner) —
 * proving out frame-based character animation in this engine before any
 * real commission exists, using a placeholder sheet a friend drew (Luffy
 * idle/run, `public/test/luffy-sheet.png`). Deliberately isolated from the
 * real game: not on `MainMenuScene`, reachable only via `?spriteTest=1`
 * (`BootScene`'s existing debug-redirect convention, same as
 * `?debugChapter=`) — nothing here is wired toward `UnitSprite`/real units
 * yet, that's a separate decision once this actually looks right.
 *
 * The sheet's frames are hand-cut, not a fixed grid — width and height both
 * vary frame to frame (`public/test/luffy-atlas.json`, generated by
 * scanning for transparent-pixel gaps rather than hand-measured; see the
 * README changelog entry for the exact method). Phaser's grid-slicing
 * `load.spritesheet()` can't handle that; `load.atlas()` with per-frame
 * pixel rects is the actual fit. Each frame is trimmed *tight* to its own
 * ink (no padding), so `setOrigin(0.5, 1)` — Phaser's origin is a fraction
 * of *that* frame's own width/height, recomputed every frame — keeps the
 * character's feet anchored to the same point across every frame without
 * needing TexturePacker-style `sourceSize`/`spriteSourceSize` padding data.
 * The ground line is here specifically to make that verifiable at a
 * glance: if trimming ever stops being tight (a future sheet with baked-in
 * padding), the feet will visibly float off it frame to frame.
 *
 * `luffy-attack.png` (2026-08-31) is a second, separate sheet the repo
 * owner added the same way — a stretch-punch sequence long enough that
 * it's laid out as two rows rather than one very wide strip, which is why
 * scanSpriteAtlas.ts grew row-band detection (was single-row-only before).
 * It also has a fist/speed-line motion trail that fades to fully-transparent
 * for a column before resuming, which the tool's `--min-fragment-width`
 * default now folds back into its real neighbor instead of reading as its
 * own tiny frame — see that script's doc comment for how this was confirmed
 * (rendered the actual pixels, didn't guess). Deliberately *not* run
 * through `--stabilize`: a stretch punch has real, intentional horizontal
 * travel as the fist extends, which is exactly the motion that flag can't
 * tell apart from drift (documented the same way after --stabilize
 * over-corrected this same sheet's `run` group during the idle-slide fix).
 * A second Sprite isn't needed for this — Phaser's `sprite.play()` swaps
 * texture to match whichever atlas an animation's frames belong to, so one
 * Sprite plays animations from either atlas interchangeably.
 *
 * `luffy-attack`'s 22 frames read (by eye, frame-stepping through the raw
 * scan) as: 0-7 a windup pulling the fist back, 8 the first punch landing
 * at max stretch, 9-10 a brief recovery, 11-17 one full punch cycle (the
 * arm re-coils compact at 11, extends out through a widening stretch,
 * peaking at 15, then starts retracting again by 17), and 18-21 easing the
 * arm back down into a resting guard. Per the repo owner: 11-17 reads as
 * one jab, not a single continuous motion, so `buildAttackFrames()` repeats
 * that slice (`ATTACK_FLURRY_REPEATS`) before continuing into the ease-out
 * — same 7 frames playing several times over reads as a flurry of jabs
 * instead of one long reach. Timing follows anticipation/snap/hold/ease:
 * held longest at the windup's cocked-back peak and the punch-8 impact,
 * fast through the flurry, slowing back down through the ease-out — see
 * the ATTACK_*_DURATIONS constants above for the exact values, set as
 * explicit per-frame `duration` (ms) rather than a flat frameRate (Phaser's
 * `Types.Animations.AnimationFrame.duration` overrides the animation's
 * frameRate for just that one frame).
 */
export class SpriteTestScene extends Scene {
  private sprite!: GameObjects.Sprite;
  private currentAnim: 'idle' | 'run' | 'attack' = 'idle';
  private currentSpeed: number = 1;
  private frameLabel!: GameObjects.Text;
  private speedLabel!: GameObjects.Text;

  constructor() {
    super('SpriteTest');
  }

  preload(): void {
    this.load.atlas(ATLAS_KEY, 'test/luffy-sheet.png', 'test/luffy-atlas.json');
    this.load.atlas(ATTACK_ATLAS_KEY, 'test/luffy-attack.png', 'test/luffy-attack-atlas.json');
  }

  create(): void {
    this.cameras.main.setBackgroundColor('#1a1a2e');
    applyDprZoom(this);

    this.add
      .text(LOGICAL_WIDTH / 2, 40, 'SPRITE SHEET TEST', {
        fontFamily: FONT_FAMILY,
        fontSize: '15px',
        fontStyle: 'bold',
        color: COLORS.textAccent,
        resolution: DPR,
      })
      .setOrigin(0.5);
    this.add
      .text(LOGICAL_WIDTH / 2, 62, 'Placeholder art (not a commission) — proving the pipeline', {
        fontFamily: FONT_FAMILY,
        fontSize: '11px',
        color: COLORS.textDisabled,
        resolution: DPR,
      })
      .setOrigin(0.5);

    const ground = this.add.graphics();
    ground.lineStyle(1, 0x3a4258, 1);
    ground.lineBetween(LOGICAL_WIDTH / 2 - 100, GROUND_Y, LOGICAL_WIDTH / 2 + 100, GROUND_Y);

    this.anims.create({
      key: 'luffy-idle',
      frames: this.anims.generateFrameNames(ATLAS_KEY, { prefix: 'idle-', start: 0, end: 3 }),
      frameRate: 6,
      repeat: -1,
    });
    this.anims.create({
      key: 'luffy-run',
      frames: this.anims.generateFrameNames(ATLAS_KEY, { prefix: 'run-', start: 0, end: 5 }),
      frameRate: 10,
      repeat: -1,
    });
    this.anims.create({
      key: 'luffy-attack',
      frames: this.buildAttackFrames(),
      repeat: -1,
    });

    this.sprite = this.add.sprite(LOGICAL_WIDTH / 2, GROUND_Y, ATLAS_KEY, 'idle-0').setOrigin(0.5, 1).setScale(SCALE);
    this.sprite.play('luffy-idle');
    this.sprite.anims.timeScale = this.currentSpeed;
    this.sprite.on('animationupdate', () => {
      this.frameLabel.setText(`frame: ${this.sprite.frame.name}  (${this.sprite.frame.width}x${this.sprite.frame.height}px)`);
    });

    this.frameLabel = this.add
      .text(LOGICAL_WIDTH / 2, GROUND_Y + 40, '', { fontFamily: FONT_FAMILY, fontSize: '11px', color: COLORS.textDisabled, resolution: DPR })
      .setOrigin(0.5);

    const buttonY = LOGICAL_HEIGHT - 180;
    const idleButton = new Button(this, LOGICAL_WIDTH / 2 - 120, buttonY, 110, 42, 'Idle', null, '13px');
    const runButton = new Button(this, LOGICAL_WIDTH / 2, buttonY, 110, 42, 'Run', null, '13px');
    const attackButton = new Button(this, LOGICAL_WIDTH / 2 + 120, buttonY, 110, 42, 'Attack', null, '13px');
    const animButtons: Array<[Button, 'idle' | 'run' | 'attack']> = [
      [idleButton, 'idle'],
      [runButton, 'run'],
      [attackButton, 'attack'],
    ];
    animButtons.forEach(([button, anim]) => {
      button.setOnTap(() => {
        this.playAnim(anim);
        this.refreshButtonAccents(animButtons);
      });
    });
    this.refreshButtonAccents(animButtons);

    // Playback-speed selector (2026-08-31, per the repo owner) — added
    // specifically to help diagnose a "feet look like they're sliding"
    // report on the idle loop: at 1x it's hard to tell apart real per-frame
    // horizontal drift (the tight-crop atlas anchors each frame's bounding
    // box at its own center, not a fixed foot point — see scanSpriteAtlas.ts's
    // doc comment) from a simple frame-rate/eye artifact. 0.1x plays each
    // frame for ~1s at the idle rate, slow enough to step through by eye.
    const speedLabelY = buttonY + 46;
    this.speedLabel = this.add
      .text(LOGICAL_WIDTH / 2, speedLabelY, '', { fontFamily: FONT_FAMILY, fontSize: '11px', color: COLORS.textDisabled, resolution: DPR })
      .setOrigin(0.5);

    const speedButtonY = speedLabelY + 24;
    const speedButtonSpacing = 88;
    const speedButtons = SPEED_PRESETS.map((speed, i) => {
      const x = LOGICAL_WIDTH / 2 + (i - (SPEED_PRESETS.length - 1) / 2) * speedButtonSpacing;
      return new Button(this, x, speedButtonY, 80, 34, `${speed}x`, null, '12px');
    });
    speedButtons.forEach((button, i) => {
      button.setOnTap(() => {
        this.currentSpeed = SPEED_PRESETS[i];
        this.sprite.anims.timeScale = this.currentSpeed;
        this.refreshSpeedButtonAccents(speedButtons);
      });
    });
    this.refreshSpeedButtonAccents(speedButtons);

    const backButton = new Button(this, LOGICAL_WIDTH / 2, speedButtonY + 50, 130, 34, 'Back', () => this.scene.start('MainMenu'), '13px');
    backButton.setAccent(COLORS.cancelFill, COLORS.buttonStroke);
  }

  /** See the doc comment above the class for the read behind this shape. */
  private buildAttackFrames(): Types.Animations.AnimationFrame[] {
    const all = this.anims.generateFrameNames(ATTACK_ATLAS_KEY, { prefix: 'attack-', start: 0, end: 21 });
    const windup = all.slice(0, 8);
    const impact = all.slice(8, 11);
    const punchCycle = all.slice(11, 18);
    const easeOut = all.slice(18, 22);

    const withDurations = (slice: Types.Animations.AnimationFrame[], durations: number[]): Types.Animations.AnimationFrame[] =>
      slice.map((f, i) => ({ ...f, duration: durations[i] }));

    const flurry = Array.from({ length: ATTACK_FLURRY_REPEATS }, () => withDurations(punchCycle, ATTACK_PUNCH_CYCLE_DURATIONS)).flat();

    return [...withDurations(windup, ATTACK_WINDUP_DURATIONS), ...withDurations(impact, ATTACK_IMPACT_DURATIONS), ...flurry, ...withDurations(easeOut, ATTACK_EASE_DURATIONS)];
  }

  private playAnim(anim: 'idle' | 'run' | 'attack'): void {
    this.currentAnim = anim;
    this.sprite.play(`luffy-${anim}`);
    this.sprite.anims.timeScale = this.currentSpeed;
  }

  private refreshButtonAccents(animButtons: Array<[Button, 'idle' | 'run' | 'attack']>): void {
    animButtons.forEach(([button, anim]) => {
      const active = anim === this.currentAnim;
      button.setAccent(active ? COLORS.successFill : null, active ? COLORS.successStroke : null);
    });
  }

  private refreshSpeedButtonAccents(speedButtons: Button[]): void {
    speedButtons.forEach((button, i) => {
      const active = SPEED_PRESETS[i] === this.currentSpeed;
      button.setAccent(active ? COLORS.successFill : null, active ? COLORS.successStroke : null);
    });
    this.speedLabel.setText(`Speed: ${this.currentSpeed}x`);
  }
}
