import { GameObjects, Scene } from 'phaser';

import { applyDprZoom, DPR, LOGICAL_HEIGHT, LOGICAL_WIDTH } from '../systems/viewport';
import { Button, COLORS, FONT_FAMILY } from '../ui/kit';

const ATLAS_KEY = 'luffy-test';
const SCALE = 5;
const GROUND_Y = 420;

/**
 * Standalone sprite-sheet-animation test (2026-08-31, per the repo owner) —
 * proving out frame-based character animation in this engine before any
 * real commission exists, using a placeholder sheet a friend drew (Luffy
 * idle/run, `public/test/luffy-sheet.png`). Deliberately isolated from the
 * real game: not on `MainMenuScene`, reachable only via `?spriteTest=1`
 * (`BootScene`'s existing debug-redirect convention, same as
 * `?debugChapter=`) — nothing here is wired toward `UnitSprite`/real units
 * yet, that's a separate decision once this actually looks right.
 *
 * The sheet's frames are hand-cut, not a fixed grid — width and height both
 * vary frame to frame (`public/test/luffy-atlas.json`, generated by
 * scanning for transparent-pixel gaps rather than hand-measured; see the
 * README changelog entry for the exact method). Phaser's grid-slicing
 * `load.spritesheet()` can't handle that; `load.atlas()` with per-frame
 * pixel rects is the actual fit. Each frame is trimmed *tight* to its own
 * ink (no padding), so `setOrigin(0.5, 1)` — Phaser's origin is a fraction
 * of *that* frame's own width/height, recomputed every frame — keeps the
 * character's feet anchored to the same point across every frame without
 * needing TexturePacker-style `sourceSize`/`spriteSourceSize` padding data.
 * The ground line is here specifically to make that verifiable at a
 * glance: if trimming ever stops being tight (a future sheet with baked-in
 * padding), the feet will visibly float off it frame to frame.
 */
export class SpriteTestScene extends Scene {
  private sprite!: GameObjects.Sprite;
  private currentAnim: 'idle' | 'run' = 'idle';
  private frameLabel!: GameObjects.Text;

  constructor() {
    super('SpriteTest');
  }

  preload(): void {
    this.load.atlas(ATLAS_KEY, 'test/luffy-sheet.png', 'test/luffy-atlas.json');
  }

  create(): void {
    this.cameras.main.setBackgroundColor('#1a1a2e');
    applyDprZoom(this);

    this.add
      .text(LOGICAL_WIDTH / 2, 40, 'SPRITE SHEET TEST', {
        fontFamily: FONT_FAMILY,
        fontSize: '15px',
        fontStyle: 'bold',
        color: COLORS.textAccent,
        resolution: DPR,
      })
      .setOrigin(0.5);
    this.add
      .text(LOGICAL_WIDTH / 2, 62, 'Placeholder art (not a commission) — proving the pipeline', {
        fontFamily: FONT_FAMILY,
        fontSize: '11px',
        color: COLORS.textDisabled,
        resolution: DPR,
      })
      .setOrigin(0.5);

    const ground = this.add.graphics();
    ground.lineStyle(1, 0x3a4258, 1);
    ground.lineBetween(LOGICAL_WIDTH / 2 - 100, GROUND_Y, LOGICAL_WIDTH / 2 + 100, GROUND_Y);

    this.anims.create({
      key: 'luffy-idle',
      frames: this.anims.generateFrameNames(ATLAS_KEY, { prefix: 'idle-', start: 0, end: 3 }),
      frameRate: 6,
      repeat: -1,
    });
    this.anims.create({
      key: 'luffy-run',
      frames: this.anims.generateFrameNames(ATLAS_KEY, { prefix: 'run-', start: 0, end: 5 }),
      frameRate: 10,
      repeat: -1,
    });

    this.sprite = this.add.sprite(LOGICAL_WIDTH / 2, GROUND_Y, ATLAS_KEY, 'idle-0').setOrigin(0.5, 1).setScale(SCALE);
    this.sprite.play('luffy-idle');
    this.sprite.on('animationupdate', () => {
      this.frameLabel.setText(`frame: ${this.sprite.frame.name}  (${this.sprite.frame.width}x${this.sprite.frame.height}px)`);
    });

    this.frameLabel = this.add
      .text(LOGICAL_WIDTH / 2, GROUND_Y + 40, '', { fontFamily: FONT_FAMILY, fontSize: '11px', color: COLORS.textDisabled, resolution: DPR })
      .setOrigin(0.5);

    const buttonY = LOGICAL_HEIGHT - 140;
    const idleButton = new Button(this, LOGICAL_WIDTH / 2 - 74, buttonY, 130, 42, 'Idle', null);
    const runButton = new Button(this, LOGICAL_WIDTH / 2 + 74, buttonY, 130, 42, 'Run', null);
    idleButton.setOnTap(() => {
      this.playAnim('idle');
      this.refreshButtonAccents(idleButton, runButton);
    });
    runButton.setOnTap(() => {
      this.playAnim('run');
      this.refreshButtonAccents(idleButton, runButton);
    });
    this.refreshButtonAccents(idleButton, runButton);

    const backButton = new Button(this, LOGICAL_WIDTH / 2, buttonY + 60, 130, 34, 'Back', () => this.scene.start('MainMenu'), '13px');
    backButton.setAccent(COLORS.cancelFill, COLORS.buttonStroke);
  }

  private playAnim(anim: 'idle' | 'run'): void {
    this.currentAnim = anim;
    this.sprite.play(`luffy-${anim}`);
  }

  private refreshButtonAccents(idleButton: Button, runButton: Button): void {
    idleButton.setAccent(this.currentAnim === 'idle' ? COLORS.successFill : null, this.currentAnim === 'idle' ? COLORS.successStroke : null);
    runButton.setAccent(this.currentAnim === 'run' ? COLORS.successFill : null, this.currentAnim === 'run' ? COLORS.successStroke : null);
  }
}
